spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
      show-sql: ${SPRING_JPA_HIBERNATE_SHOW_SQL:false}
      format-sql: ${SPRING_JPA_HIBERNATE_FORMAT_SQL:false}
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
    show-sql: false

server:
  port: 8080

logging:
  level:
    org:
      springframework: ${LOGGING_LEVEL_SPRING:INFO}
      hibernate:
        SQL: ${LOGGING_LEVEL_HIBERNATE:OFF}
        type:
          descriptor:
            sql:
              BasicBinder: ${LOGGING_LEVEL_SQL_BINDING:OFF}